const initial_data = {
    "1": "This quote means that when images are requested or needed, they are automatically adjusted or made better to fit the specific requirements at that moment. It suggests that the process of optimizing images is done quickly and without manual intervention, happening automatically when needed. This ensures that the images are of the best quality for the particular use or situation.",
    "2": "Creating or updating content without redeploying your site means making changes to the information on your webpage without having to go through the process of republishing or completely refreshing the entire website. This allows you to make small or incremental adjustments to the content on your site without the need to take the entire site offline or go through a lengthy redeployment process. It can save time and effort by making it easier to make changes on the fly without disrupting the overall functionality of the site.",
    "3": "To enable Incremental Static Regeneration (ISR) with Next.js in the app router, you need to include an options object in your fetch requests that contains a revalidate property. This property allows you to control how often a page with ISR should be regenerated. By setting the revalidate property to a specific value, you can define the frequency at which the page should be revalidated and updated with new data. This helps to ensure that your Next.js application stays up-to-date and efficient, providing a better user experience.",
    "4": "Vercel deployments can work together with your git provider to create preview links for every pull request you submit. When you make changes to your code and create a pull request on GitHub or another git platform, Vercel can automatically deploy these changes and create a unique URL where you can view and test the changes before merging them into the main codebase. This allows you to quickly and efficiently review your code changes and ensure they work as intended before they are officially added to the project.",
    "5": "Scalability refers to the ability of a system to handle growth and increased load seamlessly. This means that as more users or data are added, the system can easily expand to accommodate the increased demand without sacrificing performance. Availability refers to the ability of a system to remain operational and accessible at all times. This means that even in the event of failures or outages, the system can still continue to function and provide services to users. Performance globally refers to the speed and efficiency at which a system operates across different geographical locations. This means that regardless of where users are accessing the system from, they should experience fast response times and smooth performance. Overall, when a system is said to have scalability, availability, and performance globally, it means that it can handle growth, remain accessible at all times, and provide optimal performance to users worldwide.",
    "6": "To help you understand this quote at a level 5 understanding, let's break it down: When you use the term 'import,' it means bringing in or including something from one place to another in programming. In this case, you are bringing in a specific component called 'next/image' into the component where you want to display an image. The 'next/image' component is a built-in component in Next.js (a popular React framework) that is specifically designed for optimizing the loading and displaying of images on a website. So, when the quote mentions importing the 'next/image' component into the component where you want to add an image, it is telling you to bring in this specialized component to effectively handle images in that particular part of your website. This will help ensure that the images are loaded efficiently and displayed correctly.",
    "7": "In Next.js, when you render your application on the server side, you have two options for where this rendering can happen. The default option is the Node.js runtime with Serverless Functions, which means your application code will run on a Node.js server and the rendering will be done using Serverless Functions. The other option is the Edge runtime with Edge Functions, where the rendering will be done closer to the user, improving performance.",
    "8": "To optimize images on-demand means to adjust or enhance the images in real-time as they are requested or loaded on a website or application. This can involve compressing, resizing, or otherwise improving the images to ensure they load quickly and efficiently for users. By doing this, the overall build process (or the process of creating and displaying the website or app) becomes faster because the optimized images require less time and resources to load. This can lead to a better user experience and a more efficient website or application overall."
  }
  